### ISSUE TITLE
Add error handling and error messages

### ISSUE THREAD

**Issue by daniel-werner** [daniel-werner/php-quality-tools#1]
Add error handling to copy files, check if `composer.json` exists in the projects, add error messages if something goes wrong.

**Comment by kkarol012** [comment]
Can i help with this one?

**Comment by daniel-werner** [comment]
@kkarol012 Sure, if you could also add tests for the error conditions, that would be awesome!

**Comment by daniel-werner** [comment]
@kkarol012 Thanks!
