### ISSUE TITLE
Remove "vendor/bin" from the scripts paths

### ISSUE THREAD

**Issue by zarunet** [daniel-werner/php-quality-tools#5]
According to the [Composer documentation](https://getcomposer.org/doc/articles/scripts.md#writing-custom-commands):

> Note: Before executing scripts, Composer's bin-dir is temporarily pushed on top of the PATH environment variable so that binaries of dependencies are easily accessible.

Given this, scripts such as
```
"inspect": [
    "vendor/bin/phpcs src",
    "vendor/bin/phpstan analyze src"
],
```
could be rewritten as
```
"inspect": [
    "phpcs src",
    "phpstan analyze src"
],
```

This would allow better portability - given that the currently shipped scripts fail on Windows, due to it's horrific handling of directory separators

**Comment by daniel-werner** [comment]
Thanks @zarunet, this makes sense. If you could create a PR for this it would be much appreciated. Otherwise I'll change and test it. It should be included in the next release.

Thanks,
Daniel
